### ISSUE TITLE
Redirect to a url that includes square brackets []

### ISSUE THREAD

**Issue by jeffpaul** [tlovett1/safe-redirect-manager#201]
**Describe the bug**
We received the following from @tbenyon on [WordPress.ORG](https://wordpress.org/support/topic/redirect-to-a-url-that-includes-square-brackets/?loggedout=true):
> When saving square brackets in the Redirect To field they get html encoded.
> For example, this:
> `/blog/?categories[]=*`
> . . . get turned into this:
> ` /blog/?categories%5B%5D=* `
> 
> This redirect does not work as wanted. This happens with REGEX enabled or disabled.
> 
> I’ve tried escaping the brackets with \ but that didn’t work.
> 
> Thanks,
> 
> Tom

**Steps to Reproduce**

See above

**Expected behavior**

**Screenshots**

**Environment information**
 - Device: 
 - OS: 
 - Browser and version: 
 - Plugins and version: 
 - Theme and version: 
 - Other installed plugin(s) and version(s):

**Additional context**

**Comment by trainoasis** [comment]
we have the same issue by using regex to match `/`. Escaping with `\/` does not work. So basically Regex not working properly. Any workarounds? We are trying regex only because of the WPML related issue: https://github.com/10up/safe-redirect-manager/issues/153. Using regex would be a useful workaround, but unfortunately without using slashes not very useful. Do let me know if I can help

**Comment by jayedul** [comment]
It works anyway despite the square brackets get URL encoded. The data is available in the script. @jeffpaul Do we need to fix the visual representation of the parameters then?
<img width="728" alt="Screenshot 2023-06-26 at 1 58 29 PM" src="https://github.com/10up/safe-redirect-manager/assets/12506700/3ae675ce-ff94-4a7f-82e5-608857c6e19d">

**Comment by jeffpaul** [comment]
@jayedul could be worth fixing the visual representation as long as that doesn't impact functionality negatively
