### ISSUE TITLE
srm_redirect_only_on_404 doesn't work for many 404s

### ISSUE THREAD

**Issue by nacin** [tlovett1/safe-redirect-manager#228]
Filing a short bug report at @helen's request: When the functionality backed by the `srm_redirect_only_on_404` filter is enabled, `maybe_redirect` is hooked on `parse_request`. However, even on a page that ultimately 404's, `is_404()` is likely to return false at `WP::parse_request()` because it is before any lookups have been done in `WP::query_posts()`.

There seems to be a scenario (where no rewrite rule is matched) where 404 _might_ be set early enough for this to work occasionally, but for the most part this functionality seems to fail.

While I have not tested this, SRM should probably hook into `set_404` directly. It's more explicit and would catch precisely the scenarios where `WP` and `WP_Query` have decided a 404 will be sent.

**Comment by dkotter** [comment]
@nacin Thanks for the bug report!

Looking at this now, unless I'm misreading/mis-testing the code, it seems the hooks that fire are actually opposite of what you mention. If I return `true` to the `srm_redirect_only_on_404` filter, it should run the `maybe_redirect` method on the `template_redirect` hook. If I return `false` (or leave it alone, as that's the default), it should run on the `parse_request` hook. So the default is to use `parse_request` and for the 404 functionality, it will use `template_redirect`.

EDIT: I was testing on an older version of the plugin. The below bug I found has since been fixed. So in my testing locally, I'm not seeing an issue. Can you verify what version of the plugin you are running?

~~That said, there is a bug here with the way this filter is being used. Because the code for this is in a setup method within a class, and that method is only instantiated when the plugin itself loads, if you try and hook into `srm_redirect_only_on_404` within a theme (or a plugin that loads before SRM), your filter will never run (and thus it will always return `false`).~~

~~There's probably a few ways to fix this but a quick fix would be to have this setup method call another method that is hooked to `init`, which would then ensure any hooks attached to this filter will run.~~

~~Doing a quick and dirty fix locally to test this, I was able to return true to the `srm_redirect_only_on_404` filter and in doing that, redirects were working but only if the initially requested page was a 404 (which is the intention of this filter). Now that doesn't mean we shouldn't look at switching this from `template_redirect` to the `set_404` hook, but there is a different underlying bug that needs addressed to ensure this works properly~~

**Comment by dkotter** [comment]
Just adding another comment here to mention that this issue was fixed in v1.10.0, via this PR: https://github.com/10up/safe-redirect-manager/pull/203

Prior to that, there wasn't really a way to filter the `srm_redirect_only_on_404` value, so it would always remain as `false`, causing that functionality to never work.

**Comment by nacin** [comment]
Thanks @dkotter! I was actually filtering `srm_redirect_only_on_404` in a mu-plugin, but SRM was still loading earlier. I did look at #203 before opening this, but because like you I also misread the plugin, I wrongly tracked this down to the use of `parse_request`.

**Comment by wkw** [comment]
@nacin I'm looking into this but haven't reproduced yet. If you have a configuration which you think would trigger the failure, please pass along. Here's what I tried.

I have a page at `/notfound/`. And another at `/srm/` which is used for redirect.

My SRM config is:

```
+----+---------------+-------------+-------------+--------------+-------------+
| ID | redirect_from | redirect_to | status_code | enable_regex | post_status |
+----+---------------+-------------+-------------+--------------+-------------+
| 9  | /notfound*    | /srm/       | 302         | false        | publish     |
+----+---------------+-------------+-------------+--------------+-------------+
```

In `functions.php` I have: `add_filter( 'srm_redirect_only_on_404', '__return_true' );`

- Loading `/notfound/` (trailing slash optional) takes me to the existing page at that slug, not the redirect.
- Loading `/notfound/foo`  redirects me since it's a 404 path.

Removing the filter, both of those redirect.

Also, re:
> When the functionality backed by the srm_redirect_only_on_404 filter is enabled, maybe_redirect is hooked on ...parse_request

If you are talking about this code https://github.com/10up/safe-redirect-manager/blob/trunk/inc/classes/class-srm-redirect.php#L38-L39 it looks like that hooks to `template_redirect` and not `parse_request` when using the filter.(?)

**Comment by wkw** [comment]
I had a stale copy of this page open when I responded @nacin, disregard my comment.
