### ISSUE TITLE
Upgrade Cypress to version 13

### ISSUE THREAD

**Issue by iamdharmesh** [tlovett1/safe-redirect-manager#347]
### Is your enhancement related to a problem? Please describe.

Cypress 13 was recently released, and Cypress 12 contains some breaking changes as listed below. We need to update our tests to make them work with the latest version and fix any issues that may arise.

- [ ] Upgrade `cypress` to **13.0.0** (or latest version at the time of working on this)
- [ ] Upgrade `@10up/cypress-wp-utils` to **0.2.0** 
- [ ] Replace legacy API usage such as `Cookies.defaults` with the new replacements.

### Breaking changes we need to be aware of

- Cypress dropped support for Node.js 12
- In Cypress 12, we enforce running tests in a clean browser context through [test isolation](https://docs.cypress.io/guides/core-concepts/writing-and-organizing-tests#Test-Isolation).
- The `Cookies.defaults` and `Cookies.preserveOnce` APIs have been removed. Use the new [cy.session()](https://docs.cypress.io/api/commands/session) command to preserve cookies between tests. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dkotter** [comment]
Note that our E2E tests are failing right now due to the need to upgrade Cypress.

Our `@10up/cypress-wp-utils` package is used here but we don't load a versioned release, we load from the `build` branch. This loads the latest version which runs on a newer version of Cypress and conflicts with the version of Cypress we are using. So this is an ideal task for someone to pick up as it helps get our tests running properly again.

**Comment by iamdharmesh** [comment]
Tests are failing due to Cypress 13 upgrade in https://github.com/10up/safe-redirect-manager/pull/343, as e2e tests still using removed cookies API. Raised #349 to fix this.
